# Generated by Django 6.0 on 2026-02-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_alter_barberqueue_id_alter_booking_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_payout_settled',
            field=models.BooleanField(default=False, help_text='True if employee cut has been paid out'),
        ),
        migrations.AlterField(
            model_name='barberqueue',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
