# Generated by Django 5.2.11 on 2026-02-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_alter_barberqueue_id_alter_booking_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
