# Generated by Django 5.2.11 on 2026-02-27 05:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_employeeprofile_commission_percentage_and_more'),
        ('bookings', '0013_booking_is_reminder_sent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('booking_date', 'token_number')},
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CANCELLED'), _negated=True), fields=('employee', 'booking_date', 'booking_time'), name='unique_active_booking_time'),
        ),
    ]
