# Generated by Django 6.0 on 2026-02-25 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_notification_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Commission percentage per service', max_digits=5),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Commission flat rate or fixed amount (deprecated, use percentage)', max_digits=5),
        ),
        migrations.CreateModel(
            name='PayoutHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='payout_receipts/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='accounts.employeeprofile')),
            ],
        ),
    ]
